[package]
edition.workspace = true
license.workspace = true
name = "agere-analytics"
version.workspace = true

[lib]
doctest = false
name = "agere_analytics"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
agere-app-server-protocol = { workspace = true }
agere-git-utils = { workspace = true }
agere-login = { workspace = true }
agere-model-provider = { workspace = true }
agere-plugin = { workspace = true }
agere-protocol = { workspace = true }
os_info = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha1 = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
] }
tracing = { workspace = true, features = ["log"] }

[dev-dependencies]
agere-utils-fs = { workspace = true }
pretty_assertions = { workspace = true }
