[package]
name = "agere-file-system"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
agere-protocol = { workspace = true }
agere-utils-fs = { workspace = true }
serde = { workspace = true, features = ["derive"] }
