[package]
edition.workspace = true
license.workspace = true
name = "agere-utils-fs"
version.workspace = true

[lints]
workspace = true

[dependencies]
dirs = { workspace = true }
dunce = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tempfile = { workspace = true }
ts-rs = { workspace = true, features = [
    "serde-json-impl",
    "no-serde-warnings",
] }

[dev-dependencies]
pretty_assertions = { workspace = true }
serde_json = { workspace = true }
