[package]
edition.workspace = true
license.workspace = true
name = "agere-hooks"
version.workspace = true

[lib]
doctest = false
name = "agere_hooks"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
agere-config = { workspace = true }
agere-plugin = { workspace = true }
agere-protocol = { workspace = true }
agere-utils-fs = { workspace = true }
futures = { workspace = true, features = ["alloc"] }
regex = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["io-util", "process", "time"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
