// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderUsageSummary } from "./ProviderUsageSummary";
import type { ProviderUsageTotal } from "./ProviderUsageTotal";

/**
 * Response for `usage/read` — aggregated token usage broken down by provider.
 */
export type GetProviderUsageResponse = {
/**
 * Per-provider summaries.
 */
providers: Array<ProviderUsageSummary>,
/**
 * Aggregate across all providers.
 */
total: ProviderUsageTotal, };
