// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadItem } from "./ThreadItem";

export type ItemCompletedNotification = { item: ThreadItem, threadId: string, turnId: string,
/**
 * When true, more content is expected (tool calls are queued/in-flight).
 * Consumers should NOT finalize streaming animations.
 */
isInterim?: boolean, };
