// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileSystemAccessEntry } from "./FileSystemAccessEntry";

export type PermissionProfileFileSystemPermissions = { "type": "restricted", entries: Array<FileSystemAccessEntry>, globScanMaxDepth?: number, } | { "type": "unrestricted" };
