// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderUsageDailyBucket } from "./ProviderUsageDailyBucket";

/**
 * Aggregate totals across all providers.
 */
export type ProviderUsageTotal = { totalTokens: number, inputTokens: number, cachedInputTokens: number, outputTokens: number, reasoningOutputTokens: number, peakDailyTokens: number,
/**
 * Wall-clock seconds of the longest single turn recorded, or `None` if no turns exist.
 */
longestRunningTurnSec: number | null,
/**
 * Daily totals across all providers, sorted by date ascending.
 */
dailyBuckets: Array<ProviderUsageDailyBucket>, };
