// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderUsageDailyBucket } from "./ProviderUsageDailyBucket";

/**
 * Per-provider token usage summary with daily breakdown.
 */
export type ProviderUsageSummary = {
/**
 * Provider identifier (e.g. "openai", "anthropic").
 */
providerId: string,
/**
 * Total tokens consumed across all recorded days.
 */
totalTokens: number,
/**
 * Total input tokens.
 */
inputTokens: number,
/**
 * Total cached input tokens.
 */
cachedInputTokens: number,
/**
 * Total output tokens.
 */
outputTokens: number,
/**
 * Total reasoning output tokens.
 */
reasoningOutputTokens: number,
/**
 * Highest single-day total across all dates.
 */
peakDailyTokens: number,
/**
 * Daily usage buckets sorted by date ascending.
 */
dailyBuckets: Array<ProviderUsageDailyBucket>, };
