// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single day's token usage for a provider.
 */
export type ProviderUsageDailyBucket = {
/**
 * ISO-8601 date string (YYYY-MM-DD).
 */
date: string,
/**
 * Total tokens used on this date.
 */
totalTokens: number,
/**
 * Input tokens used on this date.
 */
inputTokens: number,
/**
 * Cached input tokens used on this date.
 */
cachedInputTokens: number,
/**
 * Output tokens used on this date.
 */
outputTokens: number,
/**
 * Reasoning output tokens used on this date.
 */
reasoningOutputTokens: number, };
