// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "../ReasoningEffort";
import type { ReasoningSummary } from "../ReasoningSummary";
import type { ServiceTier } from "../ServiceTier";

export type ThreadProviderUpdateResponse = { model: string, modelProvider: string, serviceTier: ServiceTier | null, reasoningEffort: ReasoningEffort | null, reasoningSummary: ReasoningSummary | null, };
