// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadRateLimitWaitingNotification = { threadId: string, turnId: string, attempt: number, maxAttempts: number, resumeAt: number, waitSeconds: number, reason: string, };
